language: python
python:
- 2.7
- 3.8
script:
- echo "hello"
  #- python setup.py sdist
stages:
- deploy
deploy:
  provider: pypi
  user: __token__
  password:
    secure: PvVrDkQ+C9qJ4Xah4biRTqYGhSjJyvN3jC8Nl0Wb8U+TcMidj0RSGpwW2Zjn5V9D3VzAHQwFGhMbviW4KTl09arA3mcT5OcRNlOyBgGg5H0bGrAvZg557+5TbesAvjUMhwNr+xzWlsmTf8Zugau5N+NBNpnuSRI8eNn57y246ldhzuOphEeVX+dlFXf4i0gC1nzMu0ixt7Bb36LLyJhCwjzQHXDuA/V+PS7l7FHec6nyMDIKWFxX0feZmMFEu6v+CAX6Lm2ZmhWNVYtKgejZcv26BOzbuKYAC29aYDEWMQHOCfWYo7A9VJiOK+f4sSJysAyKOvKn9lNIjTjrg/m0LQA09XnST7OY3rx1L4xU19iumsNG/tNqHsAdn8sKKBgzwPIOJU8rxBvtoen7LPcypP5cIkZ5DHNSEdzta0v5Z8iSIUYHLmFVklSycp8Qqi2aZz/uTUs/rp1EWhU778v5cOGgJ9N5xX21tpt6r7EMIW5by7z0u7xeXupMlDWiFeejbbMIuIbi3z226U6zfJpx0i3H8Dp7phN7vI/49qxguGB7u07ojwbXIgOtej8UtlcXCOcJDwCqGr46b/UdHKgt6RmgvEkAk1Ftm4v5UF5B5IcbY2djV2w6UMePmX7ALzXRsubYkl28PaUr0PrDdbfa+abZwDcC34kkly3WwBkgW8k=
